title: "Thomas Marshall"
description: "Mechanical engineering portfolio — microfluidics, test, automation"
theme: jekyll-theme-minimal

# Optional (works with the 'minimal' theme):
logo: /images/headshot.jpg
